name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: '*pending*'
          token: ${{ github.token }}

      - uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}

      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }
      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.nextMajor }}
          name: ${{ steps.semver.outputs.nextMajor }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md